def show_help():
    print("It's a docs for Ragalik")
    print("Objects:")
    print("$ = it's a bonus, give you 20 or -20 and other")
    print("S = it's spike, hit and remove moves between 5 and 15")
    print("E = An enemy, hit for 10")
    print("@ = it's a you.")
    print("O = door for next room")
    print("W = game end, victory")
    print("Commands and Actions:")
    print("w/a/s/d = standard move")
    print("exit or q = exit")
    print("bomb = explode a bomb")
    print("-moves add <number> - give a moves")
    print("-moves remove <number> - remove a moves")
    print("-bombs add <number> - add bombs")
    print("-bombs remove <number> - remove bombs")
    input("Press Enter to continue...")
